platform:ios, '7.0'
pod 'AFNetworking', '~> 1.3.3'
pod 'MMDrawerController', '~> 0.5.7'
pod 'SDWebImage', '~> 3.7.1'
pod 'ReactiveCocoa', '~> 2.4.7'
pod 'ReactiveViewModel', '~> 0.3'
pod 'Masonry', '~> 0.6.1'
pod 'BlocksKit', '~> 2.2.5'
pod 'RegexKitLite', '~> 4.0'